name: Atualizar GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Readme Stats com token
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: heraldoaraujo
          include_private: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
